### ISSUE TITLE
Midpoint age falling right on boundary

### ISSUE THREAD

**Issue by ehuangc** [palaeoverse/palaeoverse#104]
When running bin_time(method = "mid"), occurrences with a mid_ma that fall right on the boundary of two stages get an NA for their bin assignment. Is there a reasonable way to address this? If not, should the user be alerted to the issue?

<img width="556" alt="image" src="https://github.com/palaeoverse/palaeoverse/assets/71412682/dd42b215-8858-4849-99bf-63021b9257e8">

**Comment by LewisAJones** [comment]
Hi @ehuangc, what is your desired outcome here? Would you like your occurrences to be assigned to both bins, the oldest or the youngest bins, or randomly? 

You could use one of the other methods available in `bin_time`, such as `method = "all"` to assign to all bins your occurrences age range passes through. This could be used on just a subset of your data matching your occurrence records which sit on the boundary. You could also assign randomly (`method = "random") or following some probability distribution (`method` = "point"). See full documentation [here](https://palaeoverse.palaeoverse.org/reference/bin_time.html). 

We don't make these types of decisions for the user as they're likely to be user-specific, but I agree that there is value in adding a warning in such cases - we'll make sure that there is one in the next version of the package. Thanks for your feedback!
