### ISSUE TITLE
GPlates API now returns original coordinates instead of NA when outside age scope

### ISSUE THREAD

**Issue by willgearty** [palaeoverse/palaeoverse#112]
When a user submits coordinates to `palaeorotate()` with an age outside of the scope of a given model, it appears the GPlates API now returns the original coordinates instead of NA:

``` r
library(palaeoverse)
occdf <- data.frame(lng = c(2, -103, -66),
                    lat = c(46, 35, -7),
                    age = c(88, 125, 500))
palaeorotate(occdf = occdf, method = "point", model = c("PALEOMAP", "MULLER2016", "SETON2012"))
#> PALEOMAP
#> MULLER2016
#> SETON2012
#>    lng lat age p_lng_PALEOMAP p_lat_PALEOMAP p_lng_MULLER2016 p_lat_MULLER2016
#> 1    2  46  88         3.3803        36.0574           1.5367          38.9498
#> 2 -103  35 125       -54.3464        34.2684         -57.6315          28.7241
#> 3  -66  -7 500      -115.9991       -63.7982         -66.0000          -7.0000
#>   p_lng_SETON2012 p_lat_SETON2012 range_p_lat max_dist
#> 1          5.7160         40.8531      4.7957  569.989
#> 2        -47.2065         29.6023      5.5443 1018.511
#> 3        -66.0000         -7.0000     56.7982 7441.814
```

<sup>Created on 2024-03-11 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

We throw a warning when the returned coordinates are NAs, but right now we do not throw any warning when the returned coordinates are the same as the submitted coordinates.

**Comment by michaelchin** [comment]
> Hmmm, I agree that this is an issue. We could put something into place which checks age of occurrences against the model specified. However, I ultimately think that this should be resolved on the GPlates Web Service, rather than in palaeoverse.
> 
> Examples using the GPlates Web Service directly:
> 
> MULLER2016 temporal coverage = 0–230 Ma
> 
> ```
> https://gws.gplates.org/reconstruct/reconstruct_points/?lats=46,35,-7&lons=2,-103,-66&time=500&model=MULLER2016&return_null_points
> ```
> 
> SETON2012 temporal coverage = 0–200 Ma
> 
> ```
> https://gws.gplates.org/reconstruct/reconstruct_points/?lats=46,35,-7&lons=2,-103,-66&time=500&model=SETON2012&return_null_points
> ```
> 
> This issue seems to be consistent across quite a few of the models.
> 
> Furthermore, some of the models appear to rotate beyond their stated temporal range, e.g. TorsvikCocks2017 (0–540 Ma)
> 
> ```
> https://gws.gplates.org/reconstruct/reconstruct_points/?lats=46,35,-7&lons=2,-103,-66&time=600&model=TorsvikCocks2017&return_null_points
> ```
> 
> @michaelchin @sabinz is this something we could resolve on your side? I imagine this is important beyond our R package (e.g. web interfaces using the GWS).

I can check the "time" request parameter on the GWS side and return "400 Bad Request" if the "time" is out of the scope.

**Comment by LewisAJones** [comment]
Hi @michaelchin, I think that would work well! Thanks for responding so quickly.

**Comment by michaelchin** [comment]
I have update the web service server. Now the server will return "400 Bad Request" if the "time" is out of the scope.

**Comment by LewisAJones** [comment]
Thanks @michaelchin!
