### ISSUE TITLE
Make all functions tibble compatible

### ISSUE THREAD

**Issue by willgearty** [palaeoverse/palaeoverse#118]
A user noted a bit ago that one of our functions broke when using a tibble (e.g., generated by read_csv with a PBDB url). At the time we just directed them to use read.csv instead to make a dataframe. However, it looks like there are some very small things we can do to make our functions compatible with both dataframes and tibbles: https://hugogruson.fr/posts/compa-tibble/

**Comment by KEichenseer** [comment]
Good catch, Will. 

I don't recall an instance where we rely on partial matching, so all we may have to do is change lines like 
`early <- occdf[, early_interval]` to `early <- occdf[, early_interval, drop = TRUE]`?

An alternative could be to convert the input to data.frames and reconvert it to tibbles at the end of the function if it was a tibble,

**Comment by KEichenseer** [comment]
> Yeah, I think `drop = TRUE` is the low hanging fruit here. I don't think we need to modify anything to make sure we return tibbles if tibbles are supplied.

I caught an additional minor issue with tibbles not having row names. This affects only one line (in `bin_time()`), which I'll address by adding a check before assigning rownames in #119
